# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d69dc242240563f161a4b5f92153b063c669dfa9424b6bc145e999ccde3d47796676a173ded2dd0ffa2896f994676ba17e3f86580d910907b67298fa80b562db

test:
  secret_key_base: 7d9a36e75ff7720e5db3bb98a6a21079d269081e39c0e9b3578592c1b8e307dab3144c678904e1f8f1d1d788b7ee1e959b1ec065991753bd62f15b4aa367fb83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
